### PR TITLE
Markdownification

### PR DESCRIPTION
**Pull request by jeremiah**
Ooooh shiny!

### CODE REVIEW

**Comment by slawr** [comment]
That was quick! :) Thanks for the PR. 
Can you fix up the commit message to something more descriptive and add a signed-off please.
It would be great if you could do that quickly as I'm about to update the readme with some real information and push the PR to GDP.

**Comment by slawr** [comment]
Don't worry about the timing Jeremiah. I pushed the PR to update the readme but can manually merge your change when you fixup the commit msg

**Comment by jeremiah** [comment]
Hi,

I've been traveling so haven't had time to fix this. But I will! As soon as I'm home next week. 😁

**Comment by jeremiah** [comment]
I can't push to this repo. So I'll close this and send a PR from my own account.

**Pull request closed without merging**
